### ISSUE TITLE
What is the best way to suggest the addition of new stations

### ISSUE THREAD

**Issue by caiodev** [odioapp/odio#11]
I'd like to know what is the best way to suggest new stations

**Comment by spiral2k** [comment]
Hi @caiodev, odio is a streaming app that uses the online radio lists from http://www.radio-browser.info.

is an wiki like aproach to collect as much online radio stations as possible.
every one can help by not only adding new stations but also tagging existing ones.

if you want to add a station you can go to http://www.radio-browser.info.

**Comment by caiodev** [comment]
Thanks @spiral2k
