### ISSUE TITLE
[Feature]: Debug view.

### ISSUE THREAD

**Issue by eddriesen** [odioapp/odio#114]
I am able to reproduce a lot of bugs here, but how diagnose these bugs? 

There is no documented way to see debug logs, nor an option to see/generate it in-app.

Also, there's no source code available on github, to collaborative look for solutions. Is this intentional?

Would be glad to participate in diagnose some of these bugs (as a usual github project allows), but at this moment, it isn't possible.

**Comment by spiral2k** [comment]
Hi @eddriesen, wait for the next version (2.0), the public beta will be in one month.
