### ISSUE TITLE
chinese stations can't listen

### ISSUE THREAD

**Issue by novioleo** [odioapp/odio#12]
with the latest snap version.

**Comment by spiral2k** [comment]
Hi @novioleo there was a problem to stream radio stations with m3u/pls/m3u8 file types, in the next release i will be fix that, the next release will be in couple of days.

see #24.

if you think i have not fixed this issue feel free to open it again

thanks!

**Comment by spiral2k** [comment]
fixed in 1.3.5, update & check -> let me know if you have any issue, thanks!

**Comment by novioleo** [comment]
@spiral2k checked~so great work.it works for chinese statios~
