### ISSUE TITLE
[Feature]: Switch to new API before August 1, 2020

### ISSUE THREAD

**Issue by garenyondem** [odioapp/odio#121]
**Is your feature request related to a problem? Please describe.**
At radio-browser.info there is a notice of retiring a certain version API. Since odio is closed source, I wonder which version of endpoint it is consuming. Or is it going to be dead on August 1, 2020?

**Describe the solution you'd like**
Switch to new API before August 1, 2020

Quote taken from radio-browser.info
> If you still use the api at www.radio-browser.info/webservice you should switch as soon as possible to the new one at api.radio-browser.info. The old one is not supported anymore and will not receive any more updates on the software side. The new one is in place and stronger than ever (multiple servers). The api endpoints at www.radio-browser.info/webservice will be taken down at August 1. of 2020.

**Additional context**
http://www.radio-browser.info/gui/#!/

**Comment by spiral2k** [comment]
Hi @garenyondem, the next version of odio will be release to public beta in one month.

**in August 1, 2020 version 1.4 will be dead.**

odio 2.0 will use the new servers.
