### ISSUE TITLE
[Feature]: Add new radio station and report wrong Radio Station Detail

### ISSUE THREAD

**Issue by cpx2017** [odioapp/odio#128]
Hello, I'm Chinn. I'm used this app from Thailand. I want to suggest add new radio list and fixed something with Radio Detail

- Hitz955 : audio stream link here (Just copy followed link) : https://wzorigin.becteroradio.com/Hitz/Hitz-Listen-Med/chunklist_w301961432.m3u8

Hitz 955 Staion Logo : [Here](http://hitz955.becteroradio.com/assets/images/logo-top.png)

- Eazy FM 105.5's Station Logo is wrong. But that station logo is Hitz 955 Station.
Correct Station Logo : [Here](http://eazyfm.becteroradio.com/assets/images/logo-top.png)

**Comment by spiral2k** [comment]
Hi @cpx2017, odio is a streaming app that uses the online radio lists from http://www.radio-browser.info.

is an wiki like approach to collect as much online radio stations as possible.
every one can help by not only adding new stations but also tagging existing ones.

if you want to add a station you can go to http://www.radio-browser.info.
