### ISSUE TITLE
Closing Window on Mac stops streaming

### ISSUE THREAD

**Issue by snowyfox** [odioapp/odio#14]
On the Mac version of the app, when you close the window, it kills the stream you're listening to, but doesn't actually kill the app. On Mac its fairly standard for audio apps to allow you to close the window, with the expectation that the app state and audio will continue playing in the background. Clicking the apps icon on the dock will recreate the window, with the app continuing exactly where you left off. 

If the intention is for the app to only function while a window is open, then the app needs to actually quit when you close the window. Currently, the app continues to exist in the dock, and you have to manually quit the app to fully close it. 

I've included a link to an article that discusses this difference between MacOS and Windows / Linux.

https://www.howtogeek.com/279086/why-do-mac-apps-stay-open-when-i-hit-the-red-x-button/

**Comment by caiodev** [comment]
@spiral2k Maybe you could add the option of just minimizing the app to the system tray  when it's closed
in all platforms on the "Settings" section. It would be great

**Comment by caiodev** [comment]
@spiral2k Maybe you could add the option of just minimizing the app to the system tray when it's closed
on all platforms in the "Settings" section. It would be great

**Comment by spiral2k** [comment]
hi @snowyfox and @caiodev, i am using odio on MacOS and i am not sure i'm understand you correctly, when you listening and the window is open you can close the window using the red button, you can minimize it using the yellow button and the stream **will continue** in the background or you can maximize it using the green button.

when you close odio using the red button that doesn't actually kill the app because this is how MacOS work but i can change it, i can close the app completely and maybe its a good idea.

**Comment by snowyfox** [comment]
@spiral2k When I click the red button it KILLS the stream on my Mac. When I click the dock icon, it recreates the Window from scratch, along with the initial loading spinner on the window. The way you describe how Odio works on your Mac is the reason for why I'm reporting the bug. The way it works for you is how I was expecting the app to work. Clicking on the red button would close the window but allow the app to run in the background, and continue streaming. On my Mac, it does NOT continue to run properly in the background. Only reason I brought up quitting the app when you close the window was because that is how the app is basically functioning for me currently, and I assumed that was the expected behavior of the app. It sounds like this is not expected behavior, and that clicking the red button should allow for the window to close but not actually kill the main running instance of the app. 

The app acts like the main controller for everything is tied to the window itself. When the window is created, the core of the app gets initialized. When the window is closed, the initialized app is destroyed along with the window. Is the source code for the app available somewhere?

**Comment by spiral2k** [comment]
hi @snowyfox i will release the source code in the future.

you know apps with that behavior that do not close and continue  to run in the background when you clicking on the red button?

because in my experience that's not the behavior of most apps but i'm not quite sure.

**Comment by brpaz** [comment]
Same happens in Linux. It would be nice if instead of closing the window, it minimized to System Tray and to to behave like other music apps (Ex: being able to control the playback from the sound widget in the menubar. See spotify for example.

But, your app looks amazing. Congrats.

**Comment by spiral2k** [comment]
@snowyfox i have fixed that in the 1.3.0 release, thanks!

@brpaz hopefully it will be in the next version of odio

**Comment by snowyfox** [comment]
@spiral2k Just installed the 1.3.1 pre-release build and just wanted to confirm that everything works now as expected! Thanks for fixing this!!!

**Comment by odioapp** [comment]
@snowyfox great! i have added a release notes to the release, if you have more issues drop me a note.

**Comment by spiral2k** [comment]
@snowyfox happy to hear! i have added a release notes to the release, if you have more issues drop me a note.

**Comment by spiral2k** [comment]
@snowyfox you need to update to 1.3.5, i have fixed issue with the automatic updates.
