### ISSUE TITLE
Allow 2 lines of text for station name

### ISSUE THREAD

**Issue by kekukui** [odioapp/odio#15]
Too many station name strings are truncated.  Need to allow more space.

![odio truncated title bug](https://user-images.githubusercontent.com/20834957/49014819-5d9bc480-f14f-11e8-8eaa-3232c2c4f04c.PNG)

**Comment by spiral2k** [comment]
@kekukui i'm thinking on something to solve this, thanks!

**Comment by spiral2k** [comment]
fixed in 1.4.0, thanks!
