### ISSUE TITLE
Can you add a Brazilian radio station?

### ISSUE THREAD

**Issue by MarcelLeal** [odioapp/odio#17]
Hi, I would be glad if you include Morena FM in Odio, if possible. It's a nice radio station from Itabuna, Brazil and it was the first in Latin America to use only digital music, back in 1991.
site - www.morenafm.com
streaming host - 192.99.150.31
streaming port - 9407
url - http://centova2.livehost.com.br:2199/tunein/mcradio.pls

Cheers

Marcel
--

**Comment by h3298** [comment]
![odio add station request](https://user-images.githubusercontent.com/20834957/49019442-ec164300-f15b-11e8-90ad-130a7a3f4129.PNG)

**Comment by spiral2k** [comment]
Hi @MarcelLeal , odio is a streaming app that uses the online radio lists from http://www.radio-browser.info.

is an wiki like approach to collect as much online radio stations as possible.
every one can help by not only adding new stations but also tagging existing ones.

if you want to add a station you can go to http://www.radio-browser.info.
