### ISSUE TITLE
Permission denied when starting odio

### ISSUE THREAD

**Issue by farindk** [odioapp/odio#19]
I am using `odio` successfully for several weeks now, but experienced a strange glitch today when I tried to start it (Ubuntu 18.04). I got the following error message when starting it. Even stranger, it did not happen again when I tried it a second time:

    farindk@earth:/mnt/archive$ odio 
    cannot change current working directory to the original directory: Permission denied
    farindk@earth:/mnt/archive$ odio
    --> works

The current directory when starting `odio` above was on a NFS share, but I have read and write permission on that and don't have any permission problems. So I am not sure where this error comes from.

Not sure what it means with the `original directory`.

**Comment by spiral2k** [comment]
Hi @farindk, it seems that it's a known issue with NFS share and I don't think it's odio's issue:

https://github.com/heroku/cli/issues/535

https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1662552

https://forum.snapcraft.io/t/snap-doesnt-work-in-networked-environment-ubuntu-18-04-server-client/5428

**Comment by farindk** [comment]
Right, seems to be a 'snap' issue. This is where the error message seems to come from:
https://github.com/snapcore/snapd/blob/d1a896605ae0b569bf00a010479e7ed4f8fe2bd0/cmd/snap-confine/mount-support.c#L107

PS: Other than the issues on the linked web-pages, I do not have the home directories on NFS, and it was also just a non-reproducible one-time glitch.

**Comment by spiral2k** [comment]
great to hear, i'm closing this issue, have a great day!
