### ISSUE TITLE
Adjust playback buffer size

### ISSUE THREAD

**Issue by kekukui** [odioapp/odio#23]
I think buffter size is too large ; there is a long delay before playback starts.  Allow user to set buffer size.

**Comment by spiral2k** [comment]
Hi @kekukui, why you think the buffer size is too large?
the delay depends not only on the buffer size, there are stations that load almost instantly

**Comment by spiral2k** [comment]
You have station name to give me to test on windows? 

What version do you have?

**Comment by kekukui** [comment]
In bug https://github.com/odioapp/odio/issues/30 they mentioned Radio Universidad de Concepción
This station took 12 seconds to start playing.  But the next time there was no delay.  It happens randomly when I go through the 'My Stations Library' and play all the stations .  I am using 1.4.0.
