### ISSUE TITLE
Support playlist files

### ISSUE THREAD

**Issue by h3298** [odioapp/odio#24]
Support playlist files (.pls/.m3u) like VLC.  Example stations not working in Odio:

WBCQ (7.490)
WBCQ (5.130)
Dark Ambient
Revolution Radio
CJBK
CFTE
CFAX
977 music

**Comment by ewired** [comment]
Add Bassdrive to the list. It simply fails to play any station that provides an m3u despite the radio browser site fully supporting those types of stations.

**Comment by spiral2k** [comment]
I'm working on a fix for that, hopefully it will be in the next version

**Comment by spiral2k** [comment]
fixed in 1.3.5, update & check -> let me know if you have any issue, thanks!

**Comment by kekukui** [comment]
@spiral2k - **great =)**

@ewired - bassdrive does not play for me through the web interface, maybe the URL is bad
http://www.radio-browser.info/gui/#/byname/bassdrive
