### ISSUE TITLE
GTK Problems

### ISSUE THREAD

**Issue by CSAndrew** [odioapp/odio#27]
I'm aware that snap applications have a problem with GTK compliance, but I'm wondering if anyone here has found a workaround. In addition to that, I don't see any .deb or PPA versions here, so I'm also wondering if snap is the only / primary option.

**Comment by alexwender1** [comment]
Unfortunately it is .snap. But the developer is already aware to release on .flatpak. In .deb there is the problem of downloading the installer every time there are updates.

**Comment by spiral2k** [comment]
Hello @CSAndrew & @alexwender1 you can test the AppImage release (1.3.5)?
