### ISSUE TITLE
Playback issues

### ISSUE THREAD

**Issue by davidaguilerar** [odioapp/odio#30]
Hi all,

I noted that some radios (for instance in my country, Chile) fail to play, and Odio app says "There was a problem to play this station right now, please try again later". But in [Radio Browser Database](http://www.radio-browser.info), I can play these radios. 

Regards

**Comment by spiral2k** [comment]
Hi @davidaguilerar, you can give me a station name to test?

**Comment by davidaguilerar** [comment]
A example is Radio Universidad de Concepción
http://www.radio-browser.info/webservice/pls/url/17647

**Comment by h3298** [comment]
yes, duplicate of bug https://github.com/odioapp/odio/issues/24

**Comment by spiral2k** [comment]
fixed in 1.3.5, update & check -> let me know if you have any issue, thanks!
