### ISSUE TITLE
same station appears twice

### ISSUE THREAD

**Issue by farindk** [odioapp/odio#34]
Some radio stations appear twice in the station list. Ok, I understand that this may be due to double listings, different bit-rates, and so on. But this is strange:

- search for stations with the name "deutschlandfunk"
- you will get a list with 22 stations. Two of them have a 'musical note' icon.
- when playing one of them and then switching to the other one, odio does not handle them as two separate stations. I.e., buffering does not restart, but playing just continues as if one did not switch at all.

Maybe both entries link to the same URL (but then, odio could filter out duplicate URLs).

**Comment by probonopd** [comment]
Some "fuzzy logic" should be used to at least group the different streams for the same station. For example, this screenshot shows different streams for 3 radio stations.

![dlf](https://user-images.githubusercontent.com/2480569/50552252-06759c00-0c87-11e9-827a-0ad2300d269a.png)

**Comment by spiral2k** [comment]
fixed in 1.4.0, thanks!

**Comment by probonopd** [comment]
Thank you.

**Comment by probonopd** [comment]
Seems not to be entirely fixed, though:

![](https://user-images.githubusercontent.com/2480569/51275224-37650900-19c9-11e9-96b5-afb490fa410f.png)

**Comment by probonopd** [comment]
Are you already doing [this](https://github.com/segler-alex/radiobrowser-api/issues/52#issuecomment-454893229)?
