### ISSUE TITLE
Please offer AppImage for download on homepage

### ISSUE THREAD

**Issue by probonopd** [odioapp/odio#35]
Thank you very much for providing an AppImage.
Please offer it for download on the homepage.

![odio](https://user-images.githubusercontent.com/2480569/50518072-a545a100-0aab-11e9-8c60-8a0cbda811c5.png)

**Comment by spiral2k** [comment]
Hi @probonopd, the first release for AppImage is for testing, in the future it will be on the home page, thanks & have fun!
