### ISSUE TITLE
Option To Show Bitrate

### ISSUE THREAD

**Issue by KerstinMaur** [odioapp/odio#36]
What do you think of an option in the settings that shows the bitrate of the radio stream?

**Comment by spiral2k** [comment]
Hello @KerstinMaur, you have that information in the profile page of the station.

**Comment by KerstinMaur** [comment]
Ah, I see now. Thanks! 👍

**Comment by abrittaf** [comment]
Sometimes there are "apparent" station streams duplicates that are not the same. This is due to those streams are offered in different bitrates. I think it would add value to see the bitrate in any station list (favs, etc)
