### ISSUE TITLE
The app’s name means “hate”

### ISSUE THREAD

**Issue by vitorgalvao** [odioapp/odio#37]
Not sure if you’re aware (or care), but the app’s name is the literal word for “hate” in Spanish and Portuguese (in the latter it uses an accent: “ódio”).

Both languages are in the top ten most spoken languages in the world, so you might want to reconsider the name.

**Comment by spiral2k** [comment]
Hi @vitorgalvao, thanks for let me know, I appreciate it.

im aware of this ״issue" but i like the name, i see in the analytics reports that odio have alot of users in spain, italy, Portugal... so i dont think it have a negative effect.

odio if a free software that "do the job" and looks great, nobody will hate odio 😉

**Comment by kekukui** [comment]
I noticed this too, but I thought _**"so long as it works..."**_  Maybe the name could mean that we hate the other proprietary radio apps and closed station directories which do not respect our freedom.  You could call it amorradio but many others already use this.  What about **_oddio_** ? :smile:

**Comment by kekukui** [comment]
aww you closed it, I wanted to see who else comments :grin:

**Comment by vitorgalvao** [comment]
> aww you closed it, I wanted to see who else comments

There’s no point. I opened the issue in case the developer wasn’t aware and wanted to make a change. Since they are aware and want to keep the name, the issue is solved.

**Comment by kekukui** [comment]
I wanted to see how many users would prefer a name change.  I guess its not really important, just curious.

**Comment by Marl0** [comment]
> Hi @vitorgalvao, thanks for let me know, I appreciate it.
> 
> im aware of this ״issue" but i like the name, i see in the analytics reports that odio have alot of users in spain, italy, Portugal... so i dont think it have a negative effect.
> 
> odio its a **free** software that "do the job" and looks great, nobody will hate odio 😉

I'm from Spain and this is a serious issue. It sounds wrong. Try to google the word. Or better try to google images the word. Spanish is the second language in the world. Imagine your app is call "Hate", is just that what we hear.

**Comment by filipemglhs** [comment]
Actually this issue is beyond Portuguese and Spanish. The word “odio” is Galician, Italian, Latin and Spanish for “hate” and Catalan for “I hate”, while “ódio” is “hate” in Portuguese. For us, a spelling like “oddio” doesn’t make any effect, because our orthography doesn’t work like the English one. As a Portuguese speaker, it’s very weird for me to use an app with this name. I also suggest you to change this name. Anyways, your app is great and I thank you for your good job!

**Comment by ccontino84** [comment]
> Hi @vitorgalvao, thanks for let me know, I appreciate it.
> 
> im aware of this ״issue" but i like the name, i see in the analytics reports that odio have alot of users in spain, italy, Portugal... so i dont think it have a negative effect.
> 
> odio its a **free** software that "do the job" and looks great, nobody will hate odio wink

FWIW, I'm from Italy and I can tell you that the name has indeed a negative effect.
I think you should consider using a different name for your app.
