### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by logix2** [odioapp/odio#4]
I saw it's mentioned that Linux support is coming soon. I thought I'd create an issue about this so I (and anyone interested) can be notified when this is "fixed".

**Comment by odioapp** [comment]
Thanks! I'm working on it.

**Comment by spiral2k** [comment]
@logix2  i have successfully run odio on linux (ubuntu) thanks to snapcraft,
i will release odio to snap store in couple of days.

**Comment by spiral2k** [comment]
you can get odio from here [https://snapcraft.io/odio](https://snapcraft.io/odio), waiting for you feedback :)

have a great day!

**Comment by pizzadude** [comment]
Was just checking uappexplorer.com for new snaps and found this. Thanks for making a Linux version!

**Comment by spiral2k** [comment]
@pizzadude thanks dude, will love to hear you feedback.

**Comment by pizzadude** [comment]
It's pretty good.
