### ISSUE TITLE
Starred channels

### ISSUE THREAD

**Issue by fulldecent** [odioapp/odio#42]
Please 

<img width="1446" alt="screen shot 2019-01-01 at 5 21 27 pm" src="https://user-images.githubusercontent.com/382183/50576904-d0046200-0de9-11e9-86d4-0e7b0600e268.png">

**Comment by spiral2k** [comment]
My library is basicly Favorites

**Comment by fulldecent** [comment]
Ah, thank you for explaining! Works great. Perhaps consider to add the same heart icon next to My Library on the left side.
