### ISSUE TITLE
High RAM Memory Consumption

### ISSUE THREAD

**Issue by alexwender1** [odioapp/odio#46]
After a few (4-5 of use) hours, I find that the Odio app consumes almost 500mb of RAM. When run, it starts consuming 150mb. Information obtained from the System Monitor.

I believe a simple program should not have this memory leak.

Deepin 15.8+5 (Last version)
Odio 1.4 .AppImage

![captura de tela_selecionar area_20190102171904](https://user-images.githubusercontent.com/45263160/50612576-8c7d2700-0ec1-11e9-9434-34ee90e2c54a.png)

**Comment by vicsanca** [comment]
Just installed, search several channels and added to my library and...1GB of RAM used!!!.
Tested v1.4.0 beta on xubuntu 18.04.

**Comment by alexwender1** [comment]
This increase in consumption seems to occur in the exchange of stations.

I tested it again today. I used Odio for about 6 hours ... and did not close the application in any moment; and the consumption remained at a maximum of 219 Mb. At the beginning of the execution, started with 148 Mb of RAM.

I believe that the application should not exceed 50mb of consumption. For it is not a robust application.

**Comment by andersan** [comment]
Anyone else having issues with the CPU?

I tested with the radio on Rhythmbox, an app that came with Ubuntu, and it doesn't have the same high CPU usage. 

Ubuntu 18.04
Odio 1.4.0 (Beta)

This is after changing the radio station multiple times.

![Screenshot from 2019-04-25 09-14-26](https://user-images.githubusercontent.com/12814577/56742706-dd4bb080-673a-11e9-9bb3-5e8db239804e.png)

**Comment by alexwender1** [comment]
> Anyone else having issues with the CPU?
> 
> I tested with the radio on Rhythmbox, an app that came with Ubuntu, and it doesn't have the same high CPU usage.
> 
> Ubuntu 18.04
> Odio 1.4.0 (Beta)
> 
> This is after changing the radio station multiple times.
> 
> ![Screenshot from 2019-04-25 09-14-26](https://user-images.githubusercontent.com/12814577/56742706-dd4bb080-673a-11e9-9bb3-5e8db239804e.png)

Do you use the Snappy version?

I am using the AppImage version in Deepin. Average background consumption is 0.7% CPU. With user intervention, consumption rises to 20% (as soon as the station is tuned, consumption drops).

The problem I have with the application is the high consumption of RAM... Consuming 300-350MB (there are reports of 1GB!).

The developer has warned that he is rebuilding the application from scratch. Probably correcting these problems.
