### ISSUE TITLE
[Feature]: Stream-URL

### ISSUE THREAD

**Issue by ZeroDot1** [odioapp/odio#48]
Please add the possibility to see the stream URL on the following page (screenshot) and be able to copy it to the clipboard.
![bildschirmfoto zu 2019-01-04 10-37-24](https://user-images.githubusercontent.com/28985171/50681719-c444b580-100c-11e9-9446-2f1f6bbaaa8b.png)

**Comment by spiral2k** [comment]
Hello @ZeroDot1, if you want to find stream URL's you can go to http://www.radio-browser.info/gui/, odio is using the listing from radio-browser.info.
