### ISSUE TITLE
[BUG]: Sourcecode

### ISSUE THREAD

**Issue by ZeroDot1** [odioapp/odio#49]
Unfortunately I can't find any source code, so it's possible that you provide the source code, so it's possible that more people can help with the development of Odio. 

E.g. to translate #18 Odio into different languages.

**Comment by spiral2k** [comment]
Hello @ZeroDot1 odio is not open source yet, i will release the source code i just don't know when.

we can translate odio with tool like https://www.transifex.com, i will work on the localization in the coming weeks.
