### ISSUE TITLE
Directly play stations from lists & library / Other ideas

### ISSUE THREAD

**Issue by kgoldmann** [odioapp/odio#5]
What a great app, I've been looking for a simple online radio player like this for ages. The main thing I'm missing is being able to directly play stations from search results and my library without having to enter the station first. I switch between stations a lot, and every time three actions are required (click, play, back).

Perhaps the thumbnail could display a play button on mouse hover, and start playing the station, and clicking the rest of the cell opens the details view:

<img width="860" alt="image" src="https://user-images.githubusercontent.com/8964638/47431261-c03e2100-d79b-11e8-8da0-ed09da20de0f.png">

**Other feature suggestions:**

• Reordering stations in library
• Automatic switch between Dark & Light themes on Mojave
• Showing song titles & cover artwork
• Notifications for song changes
• Option of running the app via a menu bar icon

**Comment by spiral2k** [comment]
Great ideas! 

currently i'm working on the linux build of odio, but after that i will add the "play from list" feature its a must.

thank you.

**Comment by spiral2k** [comment]
the "quick play" feature released in version 1.1.0, waiting for you feedback.

have a great day!
