### ISSUE TITLE
Station does not work on Odio, but works with ffplay

### ISSUE THREAD

**Issue by bkazoo** [odioapp/odio#67]
There is a station that does not work in Odio (RAC1):
http://www.radio-browser.info/gui/#!/history/96070a75-0601-11e8-ae97-52543be04c81

However, it works when you try the same under VLC or ffplay:

$ ffplay http://streaming3.radiocat.net:80/
ffplay version 3.4.4-0ubuntu0.18.04.1 Copyright (c) 2003-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[mp3 @ 0x7fc948000b80] Skipping 52 bytes of junk at 0.   0B f=0/0   
Input #0, mp3, from 'http://streaming3.radiocat.net:80/':
  Metadata:
    icy-notice1     : <BR>This stream requires <a href="http://www.winamp.com/">Winamp</a><BR>
    icy-notice2     : SHOUTcast Distributed Network Audio Server/Linux v1.9.8<BR>
    icy-name        : RAC1
    icy-genre       : News
    icy-url         : http://www.rac1.cat
    icy-pub         : 1
    icy-br          : 48
  Duration: N/A, start: 0.000000, bitrate: 48 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, mono, s16p, 48 kb/s

http://streaming3.radiocat.net/

**Comment by spiral2k** [comment]
I will check it 👍

**Comment by bkazoo** [comment]
Thanks @spiral2k 

In case it is helpful in any way, RAC1 does not work from radio-browser itself. It works in Gradio which uses radio-broswer, though.

**Comment by kekukui** [comment]
Works for me in Odio, myTuner, and web browser
http://www.radio-browser.info/gui/#!/byname/rac1

**Comment by bkazoo** [comment]
I have checked and this is also working for me now. Thanks for looking at this.
