### ISSUE TITLE
[BUG]: Duplicate country entries

### ISSUE THREAD

**Issue by hsuehpascal** [odioapp/odio#69]
Hi, I am wondering why there are two Italian categories (Italia and Italy) and similarly two US entries (US and USA)? Though personally this causes absolutely no inconvenience, I thought this issue might interest you.

Voila the screenshot.
<img width="1302" alt="screen shot 2019-03-07 at 12 22 54 am" src="https://user-images.githubusercontent.com/31957703/53896536-28b4dd00-406f-11e9-907c-56f10b290549.png">

**Comment by alexwender1** [comment]
This is a failure of radio-browser.info; the database that Hate accesses.

**Comment by alexwender1** [comment]
This is a failure of radio-browser.info; the database that Odio accesses.
