### ISSUE TITLE
[Feature]: Possiblity of adding radio stations manually

### ISSUE THREAD

**Issue by aerospc** [odioapp/odio#89]
Would it be possible to give users the ablity of adding radio station to the program?
f.e. by having the url of that radio station.

**Comment by spiral2k** [comment]
Hi @aerospc, odio is a streaming app that uses the online radio lists from http://www.radio-browser.info.

is an wiki like approach to collect as much online radio stations as possible.
every one can help by not only adding new stations but also tagging existing ones.

if you want to add a station you can go to http://www.radio-browser.info.
